/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Convert: typeof import('./src/components/convert/convert.vue')['default']
    Descriptions: typeof import('./src/components/descriptions/descriptions.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElText: typeof import('element-plus/es')['ElText']
    JsCodeEdit: typeof import('./src/components/jsCodeEdit/jsCodeEdit.vue')['default']
    VueCodeEdit: typeof import('./src/components/vueCodeEdit/vueCodeEdit.vue')['default']
  }
}
